FROM php:8.2-fpm-alpine

# Install dev dependencies
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS curl-dev imagemagick-dev \
    libtool libxml2-dev postgresql-dev sqlite-dev

# Install production dependencies
RUN apk add --no-cache bash curl freetype-dev g++ gcc git icu-dev icu-libs imagemagick  \
    libc-dev libjpeg-turbo-dev libpng-dev libzip-dev make mysql-client oniguruma-dev \
    postgresql-libs supervisor zlib-dev

# Install PECL and PEAR extensions
RUN pecl install igbinary redis imagick

# Enable PECL and PEAR extensions
RUN docker-php-ext-enable igbinary redis imagick

# Install php extensions
RUN docker-php-ext-install bcmath calendar curl exif gd intl mbstring pdo pdo_mysql \
    pdo_pgsql pdo_sqlite pcntl soap xml zip

RUN apk add nodejs npm

# Cleanup dev dependencies
RUN apk del -f .build-deps

WORKDIR /var/www

RUN chown 1000:1000 -R /var/www
RUN mkdir /.npm
RUN chown -R 1000:0 "/.npm"

USER 1000

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

EXPOSE 9000

CMD ["php-fpm"]
